### ISSUE TITLE
enums

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#1]
Enums, as they are now, are better than in C, but could use few more improvements:

* switch on enum should be exhaustive. Possibly even more, _not_ allowed to use the default branch. This is to avoid errors when you add new enum value, and quietly, some place becomes buggy.
* enums which are used as named numbers should require all enum items to have explicit numeric value. No funny autoincrement and its restarts, no hidden bugs. No iota.
* enums with numeric value should be always sorted up when defined, just to minimize potential bugs.
* enums with numeric values could be also (distinct) floats. The limitation on integers is artificial.
* enums _without_ numeric value should be symbols only, i.e. with no way to extract a number out of them. Example:  `enum cardinal-directions { NORTH, SOUTH, EAST, WEST}` . They could be used as parameters, in switch, etc, but _not_ as named numbers. Internally, they would be implemented as numeric enums.
* repeated enum qualification in one switch branch may not be needed:

```
switch (h) 
    {
        case Height.LOW, MEDIUM: // here the second appearance of enum name is omitted
            io.printf("Not high");
            // Implicit break.
        case Height.HIGH:
            io.printf("High");
    }

```

**Comment by PavelVozenilek** [comment]
Being more precise about enum categories:

* Enum with least features. Could not be converted to a number, could not be stored in a struct or array (its size is unknown). Its just collection of symbols.
    `enum cardinal-directions { NORTH, SOUTH, EAST, WEST}
    `

* Enum which is not convertible to number, but could be part of struct/array or sent over the wire, since its size is known:
    `enum cardinal-directions : uint { NORTH, SOUTH, EAST, WEST}
    `

* Numeric enum:
    `enum cardinal-directions : uint { NORTH = 0, SOUTH = 1, EAST = 2, WEST = 3 }
    `

**Comment by lerno** [comment]
1. I would like to avoid forcing people to work in a particular way as much as possible. It can definitely be a warning, but an error is going too far. Not having exhaustive case on enum is extremely valuable, as the alternative is manually doing if-else-if constructs. As an example, the C3 compiler has a lot of cases where dispatch is on a small set of tokens and the rest are considered incorrect. Having to write all those incorrect cases every time would be rather wordy. It also brings the language too far from C.
2. Enums as named numbers: the common use for me is actually to put a zero on the first one and set that one to the invalid status. The other is to start at 1 and implicitly have zero as "non-initialized state". I don't want to prevent people from using that pattern if they want to. Again, adding an option to issue warnings or errors on this is fine, but nailed down as part of the language it goes to far away from C.
3. Again, as optional warning / error this is fine.
4. What I think you're looking for is to have an opaque enum. Since `@opaque` will be part of the language anyway (for structs / unions) it makes sense to be able to use that on enums as well, it would give you the functionality you want.
5. It might even be possible to allow complete folding of the enum namespace as in java. So `case LOW:` as long as the expression is known to be a particular enum.

**Comment by PavelVozenilek** [comment]
I personally prefer to reduce potential for bugs.  Warnings are not the best tool, either they get disabled en masse, or special syntax to mute them individually is invented, making the code more messy.

I have no idea what `@opaque` could be (there's no mention in the docs), but it sounds like annotation. These things tend to multiply (in C as const/volatile) and bring lot of complexity for little to no gain.

**Comment by lerno** [comment]
Adding the ability to set things as errors should be sufficient or? If you prefer something to be an warning or error then set that flag in your build settings. Others can do it differently, live and let live.

`@opaque` is indeed an attribute. They're not in the docs because I haven't completely reviewed the idea yet. But yes, instead of - like c - introduce keywords for things like custom alignment, struct packing etc, all uses the `@<attribute>` syntax like:

```
struct Foo @packed @opaque
{
    int i;
    byte b;
    int j;
}
```

It would also be possible to create user defined compile time annotations.

**Comment by PavelVozenilek** [comment]
I personally do not like ability to fiddle with warnings. In my code it ends like:

```
#ifdef _WIN32_
#  pragma warning (push, 2034) // this is stupid warning X
#  pragma warning (push, 8122) // silly warning Y
#elif ....
... // other platforms
#endif

... // the code

#ifdef _WIN32_
#  pragma warning (pop, 2034) 
#  pragma warning (pop, 8122) 
#elif ....
...
#endif

```
which adds impressive amount of noise. Visual C++ is very fond of warnings, generates them at every opportunity. If they envisioned warnings makes the code better, they were mistaken.


I prefer enforced strict rules. Less ambiguity, less noise, less bugs.



About padding/align attributes I'll make another post, to keep this on topic.

**Comment by lerno** [comment]
Well, yes, that is very noisy, which is why supressing warnings will look like this:

```
/// @supress(enum-conversion)
int i = cast(int, the_enum);
```

Warnings are supressed on a file, declaration or line scope using doc comments.

**Comment by PavelVozenilek** [comment]
I do not like this either, but that's just my opinion. Let settle it this way.

Numeric enum would be expected to be convertible to a number, warning is not needed, non-numeric enum would not be convertible.

**Comment by lerno** [comment]
I'd like to understand what you want to achieve by this. What errors do you want to avoid? There is indeed an issue with this:

```
enum State
{
    RUNNING,
    STOPPED
}

switch (state)
{
    case State.RUNNING:
        ....
    case State.STOPPED:
        ....
    default:
        /* handle erronous data */
}
```

And then someone updates this to:
```
enum State
{
    RUNNING,
    STOPPED,
    PAUSED
}
```

And the default then accidentally makes the missing case "disappear".

Is that the error you'd like to address?

**Comment by lerno** [comment]
In the above code there are two possibilities:

(a) add `unreachable` to the language. So here:

```
switch (state)
{
    case State.RUNNING:
        ....
    case State.STOPPED:
        ....
    default:
        unreachable;
}
```

We'd get an error if `PAUSED` is added. However, this doesn't cover the case where you have something like 
```
enum State
{
    RUNNING = 1,
    STOPPED,
    PAUSED
}
```

Where the uninitialized status is indeed 0, but you don't want to use that in the enum definition because the state should not be possible to reach for an initialized struct.

In that case we could in some way annotate either the switch (that it needs to have `case` for all cases explicitly) or on the default (that it should not catch any enum cases). That way the compiler can emit an error if it happens.

**Comment by PavelVozenilek** [comment]
That `unreachable` thing sounds good. I would use `assert` which is understood by the compiler (i.e. it is not just some function/macro).

```
switch (state)
{
    case State.RUNNING:
        ....
    case State.STOPPED:
        ....
    default:
        assert(false);
}
```
The compiler would understand what `assert(false)` means, and translate it for itself as a hint of full enum coverage.

-----------

`assert` could be used to implement many, many things (like non-nullness  constraint), without the need to invent new syntax. It is even more flexible than special syntax since it can be used only in specific cases. I'll make topic for this at some time.

(I once thought about designing language of my own, and assert awareness was one of best features I invented.)

**Comment by lerno** [comment]
Please file this in c3docs.
