### ISSUE TITLE
Feature request--easy way to import/include c headers

### ISSUE THREAD

**Issue by LukyGuyLucky** [c3lang/c3c#1126]
With c++ we can use extern "C" and directly #include header.h; Zig has something like @cImport(...) and then can directly interop c headers and sources.Both C++ and Zig doesn't have to write a wrapper before import c .

I would like to expect there is a similar way in c3 to seamlessly interact with c,at lease in one way,ie. import/include c files directly.
Or a translation tool/switch options provided by  c3c compiler would help a lot.Please note not everyone is capable to write wappers for system c files,or third party c wappers,some has very complicated structures,macros,etc.

Incapable to directly use c in c3 make me feel like although they are one family,but a visible gap stops directly shaking hands.

**Comment by lerno** [comment]
So in the Zig case, while it can do cImport, this is not working perfectly in that it can't properly convert all the macro behaviour. 

Likewise there are some things from C header files that can't be *automatically* converted for C3 use. Note my use of "automatically" here. Manual conversion is straightforward, but guaranteeing perfect automatic conversion is impossible really.

So the question becomes: should a compiler have a built in *automatic* step that only sometimes works, and essentially ties the language to the latest C standard?

I think the answer to that should be "no". Zig does this by bundling the entire Clang with its compiler, something I don't really want to do.

HOWEVER, an external tool that takes C code (headers, source files) and translates what it can to C3, that would be very valuable, and that is planned.

But for such a tool I would expect it to translate maybe 90% with the remainder being manually fixed by the user.

Finally, the cImport functionality is really just a temporary solution for bindings. In general it is too imprecise tool a to be useful for any serious project, so the value is more about the perception of interop for Zig.

After this I'd like to briefly show what you'd do to access C code from C3 if you just want something quickly.

Let's say we see this:
```c
void copy_begin(void);
void copy_end(void);
Expr *copy_expr_single(Expr *source_expr);
Decl **copy_decl_list_single(Decl **decl_list);
Decl **copy_decl_list_single_for_unit(Decl **decl_list);
Attr **copy_attributes_single(Attr** attr_list);
Decl *copy_lambda_deep(Decl *decl);
Ast *copy_ast_single(Ast *source_ast);
```

First add `extern fn` and remove any `(void)`:

```c
export fn void copy_begin();
export fn void copy_end();
export fn Expr *copy_expr_single(Expr *source_expr);
export fn Decl **copy_decl_list_single(Decl **decl_list);
export fn Decl **copy_decl_list_single_for_unit(Decl **decl_list);
export fn Attr **copy_attributes_single(Attr** attr_list);
export fn Decl *copy_lambda_deep(Decl *decl);
export fn Ast *copy_ast_single(Ast *source_ast);
```
Now we're almost done, but we need some of these structs too, in C they're for example:
```c
typedef struct
{
	Decl *decl;
	Signature *signature;
	struct FunctionPrototype_ *prototype;
} TypeFunction;
```
So, strip the typedef and move the name:
```c
struct TypeFunction
{
	Decl *decl;
	Signature *signature;
	struct FunctionPrototype_ *prototype;
}
```
Finally we need no forward declaration:
```c
struct TypeFunction
{
	Decl *decl;
	Signature *signature;
	FunctionPrototype *prototype;
}
```
And we're done.

**Comment by LukyGuyLucky** [comment]
Although I am a language beginner and late learner,I do understood  & fully agreed with all your point.And the above guideline  is valuable!!!And it is something I'd love to learn.

Could you please brefing things about c marcos,esp. marco functions? I once tried to do this similar in another language with curl,but had to gave up when I encountered curl_set_opt(...) which heavily made use of macro functions if I recall correct.

Thanks and best regards

**Comment by lerno** [comment]
Well, for C macros it kind of depends. There are C macros which just act as aliases, and for this C3 uses `def` which can create a name alias. They can also act as compile time functions, in which case you'd use a C3 macro. Or it might be a generic function, and then again you can use a macro. But it depends a lot from situation to situation.

**Comment by LukyGuyLucky** [comment]
> Well, for C macros it kind of depends. There are C macros which just act as aliases, and for this C3 uses `def` which can create a name alias. They can also act as compile time functions, in which case you'd use a C3 macro. Or it might be a generic function, and then again you can use a macro. But it depends a lot from situation to situation.

Thank you for the patience.
