### ISSUE TITLE
Cannot compile to exe file.

### ISSUE THREAD

**Issue by HongChenLuYuan** [c3lang/c3c#1201]
I can't compile source files into ".exe" executable files in windows, it just generates many ".obj" files.

**Comment by lerno** [comment]
How do you invoke the compiler?

**Comment by HongChenLuYuan** [comment]
I use the "init" command to generate a project, and then run the "c3c build" command, which generates many ".obj" files, but no ".exe" executable files.
Then I found the "main.c3" file and executed "c3c compile main.c3", but still only generated many ".obj" files.

It looks like this. What should I do?
![1](https://github.com/c3lang/c3c/assets/94300434/55caf68e-fe02-4e9f-bb8d-2390b9c785f4)
![2](https://github.com/c3lang/c3c/assets/94300434/65bc5d7e-f41d-40e1-8bbe-0549c57462d5)

**Comment by lerno** [comment]
Hmm.. let's add some logs and see try adding --print-linking and --debug-log. Because what you're seeing is that it fails to link. One possibility is that the compiler does something bad when it invokes the linker and the object files are in a different drive from the compiler. Another possibility is that you didn't download the msvc libs for linking, but that should have created an error.

**Comment by HongChenLuYuan** [comment]
I added --print-linking and --debug-log. but it only outputs INFO log without any error message. 
I think I should give up trying it.

**Comment by lerno** [comment]
Can you provide me with the output you get?

**Comment by lerno** [comment]
This might have been improved in `dev`, but it's hard to tell without testers.

**Comment by HongChenLuYuan** [comment]
> Please try 0.6.0

It can work. Please forgive me for not executing "msvc_build_libraries.py", I didn't know it was necessary.

**Comment by lerno** [comment]
Did it work only after running the python script?

**Comment by lerno** [comment]
I'm closing this for now.
