### ISSUE TITLE
Program fails to compile if `output` has whitespace and the target type is `executable`

### ISSUE THREAD

**Issue by Halen84** [c3lang/c3c#1283]
In `project.json`, the program fails to compile if `output` has whitespace (e.g a folder with spaces in the name) and target type is `executable`.

Example Path: `C:\Folder\Some Other Folder`
`output` in `project.json`: `"C:\\Folder\\Some Other Folder"`
Target Type: `executable`
#
Error message: `'C:\Folder\Some' is not recognized as an internal or external command`

**Comment by lerno** [comment]
This is a problem in particular when using `system` and related functionality invoking the windows OS from C. The whole thing is implemented here in execute_cmd and execute_cmd_failable. Both these should be improved to be rock solid for windows.
However, my windows environment is poor, so this is something that I would love some contribution to get right.

(Also, I think there are places where the drive is not handled correctly either for Windows)

**Comment by SeamusMullan** [comment]
Just to add onto this, I've managed to build a project with the `output` set to a folder *not* beginning with `C:\\` or any other drive letter for that matter

using only `"output": "build dir"` functioned correctly. I have also noticed that once a directory exists, a subdirectory with a whitespace in the name *can* be made. eg.

This works fine, resulting in a subdirectory with whitespace

> running `c3c.exe build testproject` with `output = "build dir"`
> then running  `c3c.exe build testproject` with `output = "build dir\\other dir"`

however this does not and results in the original error

> only running  `c3c.exe build testproject` with `output = "build dir\\other dir"`

Hopefully that gives some insight into this problem, its a bit of an odd one and i think its mostly windows being windows ¯\_(ツ)_/¯

**Comment by lerno** [comment]
So maybe this is due to mkdir not working as expected on windows?

**Comment by prithvidiamond1** [comment]
I have tried to diagnose this problem on my end.

@Halen84's problem is not reproducible in my local environment. I can create a build anywhere and with any path (that includes white spaces for directories) so long as the path **exists** i.e. everything except the last directory in the path must already be present. This is exactly what @SeamusMullan experienced. However, this is expected behavior as the `CreateDirectoryW` function's [documentation](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createdirectoryw) explicitly states this behavior, see the description for the `ERROR_PATH_NOT_FOUND` return code.

@lerno I am no Windows expert, but after looking at the `execute_cmd` and `execute_cmd_failable` functions, nothing about them stands out as wrong. So, I am not sure rewriting the functions would solve this problem magically without knowing what the root cause of the problem is. If we could get more specifics to reproduce the problem, we would be in a better position to decide on what to do.

**Comment by rexim** [comment]
Recently we replaced `system` with a custom process spawner in #1296. So maybe this problem is fixed now?

**Comment by Halen84** [comment]
Can confirm, this is now fixed
