### ISSUE TITLE
Is linking still broken?

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#131]
`c3c compile helloworld.c3`
```TODO // fix failable
TODO // fix failable
-- AST/EXPR INFO --
 * Ast memory use: 8kb
 * Decl memory use: 24kb
 * Expr memory use: 25kb
 * TypeInfo memory use: 6kb
 * Token memory use: 1kb
 * Sourceloc memory use: 24kb
 * Token data memory use: 16kb
-- ARENA INFO --
 * Memory used:  14111 Kb
 * Allocations: 771
Segmentation fault.```

I remember that linking earlier worked, but I don't remember which commit.

**Comment by lerno** [comment]
Ok, apparently you get the segmentation fault due to multithreading there. I need to check that. There are two problems when I compile (1) it doesn't use -fPIC even though it's on Linux (which is a bug, -fPIC is expected by default on Linux it appears, so that should not be needed) (2) for some reason it complains that log10 is not available. Which is strange since I'm including -lm

I removed -fPIC as command line option but I restored it again. So do try to do a pull and add -fPIC.

You should then be able to link it with 

`cc -lm -o foo.out helloworld.o std.runtime.o std.builtin.o std.io.o std.mem.o std.array.o`

(Despite the crash)

**Comment by data-man** [comment]
Files `std.io.o` and `std.mem.o` don't exist after compilation.

**Comment by lerno** [comment]
In compiler.c there's `#define PTHREAD 1` change that to `#define PTHREAD 0`

**Comment by data-man** [comment]
Yes, ok without PTHREAD.

`c3c compile -fPIC helloworld.c3`

> Program linked to executable 'foo.out'.

**Comment by data-man** [comment]
Unrelated but `helloworld` is expected instead of 'foo.out'

**Comment by lerno** [comment]
Are you able to debug and see where things break when using threads? It works on Mac but clearly not on Linux. Strangely enough it does seem to work for a few outputs and then it breaks.

**Comment by data-man** [comment]
What version of `llvm` are you using?
I'm using `11.1.0`. Could this be the reason?
Unfortunately version 12 is not yet available on Arch (and Artix) Linux.

**Comment by lerno** [comment]
I found the issue with multithreading now, so that should work.

**Comment by data-man** [comment]
Thanks!
For gcc 12 I added `-Wno-alloc-zero -Wno-array-bounds` to `CMakeLists.txt`.

**Comment by lerno** [comment]
That was on Release, right? Somehow GCC has big problems with those on release.

**Comment by data-man** [comment]
> That was on Release, right?

Yes.

**Comment by lerno** [comment]
I've now pushed a new version that fixes that issue and also added Release to CI

**Comment by data-man** [comment]
CI uses 9.3.0?

**Comment by lerno** [comment]
It seems like that's the default. It's possible to pull more recent versions I guess.
