### ISSUE TITLE
libc structs

### ISSUE THREAD

**Issue by lucas-mior** [c3lang/c3c#1376]
How am I supposed to work with structs defined in libc headers?
For instance `struct dirent`. Do I need to copy and paste from my system headers, and then adapt them to c3 syntax, in order to call the associated functions correctly? Or is there a simpler way?

**Comment by lerno** [comment]
Lots of libc structs and functions are already available, look in /std/os and /libc.c3

If you need something that's not there, then yes, the solution is to copy the struct definitions and just place them in your code as normal structs. Note that you might need to change the name, but otherwise they should be identical. The only difficult thing can be to track down the actual definition in some cases. But look at the code in the /std/os folder and libc.c3 for a lot of examples and it should become obvious.

**Comment by lerno** [comment]
Note that in the case of something like dirent, it's not in libc, but is posix, and as such will not be in libc.c3. Dirent is available as Posix_dirent in std/os/posix/files.c3

**Comment by lerno** [comment]
Can I close this issue?
