### ISSUE TITLE
Compile time slicing of strings does not work in $eval

### ISSUE THREAD

**Issue by rexim** [c3lang/c3c#1401]
Do I understand correctly that as of right now there is no way to do compile time slicing of strings? Something opposite to `$concat` sort of speak. `$s[$start..$end]` is considered a runtime expression.

**Comment by lerno** [comment]
No, that should be possible. File a bug?

**Comment by rexim** [comment]
bug.c3:

```c
import std::io;

macro test($name) {
    int ab;
    $eval($name[0..1]) = 69;
    io::printn(ab);
}

fn void main() {
    test("abc");
}
```

```console
$ c3c compile bug.c3
 2: 
 3: macro test($name) {
 4:     int ab;
 5:     $eval($name[0..1]) = 69;
              ^^^^^^^^^^^
(/home/rexim/Programming/probe/c3-compile-slice/bug.c3:5:11) Error: Expected a compile time expression.

 7: }
 8: 
 9: fn void main() {
10:     test("abc");
        ^^^^^^^^^^^
(/home/rexim/Programming/probe/c3-compile-slice/bug.c3:10:5) Note: Inlined from here.
```

Please let me know if I'm doing something too stupid. :D

**Comment by rexim** [comment]
Updated the title to emphasize that this is bug.

**Comment by lerno** [comment]
I've reworked a lot of the code and there are some interesting complications.

First of all I tackled this as a general problem of slicing any compile time constant. So for example doing this at compile time: `(int[6] { 1, 22, 33, 4, 55, 66 })[2..4]` (or the equivalent, like `$b[2..4]` for $b containing the same array).

However, in general slicing anything will produce a slice, which lacks a length. So `$b[2..4]` should internally be an `int[3] { 22, 33, 4 }` but have the type `int[]`.

It is tempting to say that runtime slicing `$b[2..4]` produces an `int[3]`, but since an array doesn't implicitly convert into a slice, that's somewhat problematic.

So there are roughly 3 possibilities:

1. Allow compile time slicing of arrays and vectors, and have them produce slices, but add support for "compile time slices" (beyond bytes and Strings)
2. Allow compile time slicing of arrays and vectors but have them produce arrays. However, constant arrays may be implicitly converted to slices (this is not that weird, this is already ok: `int[] a = { 1, 2, 3 };`
3. Only allow compile time slicing on String and bytes constants.

Any opinion on what you would prefer?

**Comment by lerno** [comment]
Compile time slicing should now work. I'll add a new issue for the remaining.

**Comment by lerno** [comment]
Slicing untyped lists is also implemented now.

**Comment by Caleb-o** [comment]
@lerno the original example:
```c++
import std::io;

macro test($name) {
    int ab;
    $eval($name[0..1]) = 69;
    io::printn(ab); // 69
}

fn void main() {
    test("abc");
}
```

Will now compile and run as intended and print 69 as expected.
