### ISSUE TITLE
Segfault using ternary with no assignment

### ISSUE THREAD

**Issue by Dodzey** [c3lang/c3c#1468]
Repro:
```
fn void foo() {}
fn void bar() {}

fn void main()
{
    bool b = true;
    true ? foo() : bar(); // ok
    b ? foo() : bar(); // segfault
}
```

**Comment by lerno** [comment]
Should be fixed now.

**Comment by SadeAli** [comment]
The fix for the reported issue has been tested using the code snippet provided in the original report.

### Using version 0.6.2 (release):
```
➜  c3c_lts compile-run ternary_seg_fault.c3 
[1]    3838 segmentation fault (core dumped)  /path/to/c3c compile-run ternary_seg_fault.c3
```

### Using version 0.6.2 (master branch):
```
➜  c3c compile-run ternary_seg_fault.c3 
Program linked to executable 'ternary_seg_fault'.
Launching ./ternary_seg_fault
Program completed with exit code 0.
```
### Conclusion:
The fix seems to be effective, as no segmentation fault was encountered on the master branch. Please let us know if further testing is required.

**Comment by lerno** [comment]
Thank you, I'll close it.
