### ISSUE TITLE
Conditional compilation of top level declarations

### ISSUE THREAD

**Issue by ellipse12** [c3lang/c3c#1470]
At the moment the only ways to include or exclude top level declarations is either:
```c3
fn void foo() @if(...);
```
or 
```c3
module foo::bar @if(...);
//declarations and functions
module foo::bar; //return to the normal module
```
And while both of these are fine for a small number of declarations the first one quickly becomes unmanageable and the second is unclear with a large number of similar patterns, and while you can structure your code to use modules in other files and other things like that it becomes difficult to do that when converting from C. I would propose  that either allowing the `$if` macro to work at the top level or adding a separate one for this purpose. (Something like `$ifdef` or similar)

**Comment by lerno** [comment]
The second pattern is the intended one. Can you explain why this is less clear than $if / $endif? I explicitly removed `$if / $endif` from the top level because it was hard to work with when scaling up and writing conditionally compiled code in the standard library. So `@if` is due to my problems using `$if`, which is why I am interested in why you're seeing issues with this.

**Comment by ellipse12** [comment]
I just find it less clear and kind of verbose for stuff inside a module (it's great for conditionally including an entire module). I've needed it for the vulkan bindings where I'm adding support for the extensions, but they generally heavily rely on something like `#if defined(EXTENSION)` to include them, and since I am not going to convert 18000 lines of code by hand I've been using scripts to convert. I also wanted to keep it fairly similar to the original source but with the second one it is harder to tell as to where the declarations end. But this is my opinion so take it as you will.

**Comment by lerno** [comment]
Can't `#if defined(EXTENSION)` be automatically turned into `module foo::bar @if($feature(EXTENSION));`?

**Comment by lerno** [comment]
And then `#endif` becomes `// end EXTENSION features`

**Comment by lerno** [comment]
Yet another method is this:
```c
module com::foo::thelibrary;
extern fn void someFunction();
/* ... common things */
module com::foo::extension::thelibrary @if($feature(EXTENSION));
extern fn void someExFunction();
/* .. extension things */
```

Now in this case the extension and the normal lives in different modules, but share the same shortpath `thelibrary`:
```c
thelibrary::someExFunction();
thelibrary::someFunction();
```

**Comment by ellipse12** [comment]
Also what problems were you having with top-level ifs?

**Comment by lerno** [comment]
@ellipse12 Anything with `$if` or `@if` at the top level will be subject to ordering issues. Consider:
```c
$if $defined(bar):
int foo;
$endif
$if $defined(foo)
int bar;
$endif
```
Now this is obviously a circular definition, but in the case of $if, it's harder to detect as what it inside `$if` can be anything top level, including nested `$if`.

Now the "common sense" approach would be to resolve $if from "top to bottom". Which seems reasonable until one realizes that there is no well defined ordering between files. Modules are spread over multiple files, so the "top to bottom" just doesn't work well and is arbitrary. We want to catch such arbitrary resolution and make them into errors rather than having them work "sometimes". Unfortunately `$if` is a very poor way of modelling this.

There is also no way to selectively allow `$if` on particular top level statements and not on others – which is the desirable behaviour.

The way it worked in the compiler was this:
1. Register all top level constructs not in `$if`
2. In arbitrary order, check `$if` and move the internal top level constructs into a list.
3. Register all constructs in this list
4. Goto 2 if this list had more than zero entries.

Furthermore, in a lot of cases we had entire files that would be only for one platform or the other, it would look like:
```c
module abcd;
$if (env::WIN32):
   int a = ...
   ....all the declarations...
$endif
```
This was kind of bad, but the worst was when there was just a single function here and there that optionally were included.

In addition to this `$if` could not be easily accommodated to work inside of definitions, there was no:
```c
struct Foo
{
  $if ABCD:
     int a, b;
  $endif
  int d, ef;
}
```
Because that was extremely invasive in the grammar. So it was rigid and bulky.

**Comment by lerno** [comment]
The last one there with `@if`:

```c
struct Foo
{
  int a, b @if(ABCD);
  int d, ef;
}
```

What you had to do prior to `@if` was duplicate them:

```c
$if ABCD:
struct Foo
{
  int a, b;
  int d, ef;
}
$else
struct Foo
{
  int a, b;
  int d, ef;
}
$endif
```

**Comment by ellipse12** [comment]
Oh ok that make sense, so it could be possible if the definitions are only defined for macros themselves. For example you could add a macro (`$def` for example) that just adds the definition to a set then could have a separate macro for checking that list and including something based on that (not asking for this just spitballing)

**Comment by ellipse12** [comment]
It wouldn't fix the struct stuff but you could still have the @if attribute (though I can't remember if that works with struct members anyway)

**Comment by lerno** [comment]
> Oh ok that make sense, so it could be possible if the definitions are only defined for macros themselves. For example you could add a macro (`$def` for example) that just adds the definition to a set then could have a separate macro for checking that list and including something based on that (not asking for this just spitballing)

I am not sure what you mean here.

**Comment by ellipse12** [comment]
Nevermind I forgot that c3 is not linear like c

**Comment by ellipse12** [comment]
thanks for you're explanation and patience!
