### ISSUE TITLE
C3 Compiler does not recognize lib's unless specifically in a C3 Project

### ISSUE THREAD

**Issue by A7e3** [c3lang/c3c#1478]
When making a project and importing libs the compiler works as intended but when using a single c3 file/not a dedicated project and trying to build and import libraries even if the library is in the same directory and you give the path to the compiler it still won't recognize the library/import it.

I didn't read if this was intentional behavior but if it is that is kind of stupid.

**Comment by lerno** [comment]
When you say "lib" do you mean a static/dynamic library or a .c3l library?

**Comment by A7e3** [comment]
> When you say "lib" do you mean a static/dynamic library or a .c3l library?

Anything I have tried using a .c3 and a c3l it does not import into the main.c3

**Comment by lerno** [comment]
Oh, `-l` is for static libraries. Use `--lib raylib5`

**Comment by A7e3** [comment]
> Oh, `-l` is for static libraries. Use `--lib raylib5`

So, Yeah that fixes it for .c3l files but if you want to import another c3 file that does not work.

**Comment by lerno** [comment]
Can you explain what you mean by "import another c3 file"? Presumably you don't mean: `c3c compile-run main.c3 other_file.c3 --lib raylib5` or?

**Comment by A7e3** [comment]
Ok what I mean, in a project you have the main.c3 file right? if you have another .c3 file in the directory of the main.c3 Presumably  the src directory then it lets you import it without a command but if you don't have a project and try and import another c3 file even if the file is in the same directory it can't find it. you need another command in the compiler.

**Comment by lerno** [comment]
Yes, this is because in the project there is already a directory specified, which it compiles all the folders in. If you just type `c3c compile-run main.c3 other_file.c3 --lib raylib5` then you haven't specified a directory but two files (the same is possible with the project)

If you want to compile all the c3 files in the current directory you therefore need to give the directory name rather than the explicit files. So:
`c3c compile-run . --lib raylib5`

**Comment by A7e3** [comment]
Ok I did not know of this Thank you.
