### ISSUE TITLE
Support ad hoc function and type submodule declarations

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#1513]
Possible syntax
```c
module std::foo;
// Creates a sub module std::foo::bar in which hello() is placed.
fn void bar::hello() 
{
  ...
}
```

**Comment by Caleb-o** [comment]
Assuming this only allows a single level of depth? So you can do `bar::hello()` but maybe not `bar::baz::hello()`?

**Comment by lerno** [comment]
Exactly, it will be limited to single level for readability and also implementation should be more straightforward.

**Comment by joshring** [comment]
If we look at the OOP world, do they ever create an implicit class in this sort of manner? 
Personally I think a module is a fundamental organisational unit, I wouldn't want to create one implicitly, possibly by accident. I would always want to know I made an organisational unit and that I can use that further to do other interesting things with it.

I would want to be able to search for it, with `module bar::new_module;` to be able to find it.

Having things created without knowing we create a "mistrust" of modules as they are not solid things I can easily look up. I feel like this would be a grave mistake.

**Comment by Caleb-o** [comment]
@joshring I feel like this is somewhat similar to declaring nested namespaces and classes. In something like C# and Java I believe, I could make a whole lot of nested classes and namespaces. I don't think this is too different from that, except this proposal only allows for a single level of depth.

Talking about OOP, I think something like Java allows you to just make anonymous classes and such, which might go against your searchability argument. So there's definitely worse options that other languages allow and this seems pretty reasonable from what I understand.

**Comment by joshring** [comment]
This is still fairly explicit though:
```c#
public class Container
{
    class Nested
    {
        Nested() { }
    }
}
```
and you can search for `class Nested`

**Comment by joshring** [comment]
I think Java as one of the heavyweights of OOP can define some slightly non-ideal things and that's still OK. But modules are still very new as a concept to most people, so that same freedom may not be granted to us.

**Comment by Caleb-o** [comment]
I think there is one point that makes `foo::bar()` more obvious to what it is and that's the `foo::`. As far as I'm aware, the only thing that uses `::` are modules. So you declare modules using this and also qualify things this way. Since this is used at the declaration, I feel like that might be more obvious than if it were to use some other pattern. So if I saw a function declaration with `fn void foo::bar() {...}` then I would probably assume it has *something* to do with modules, then eventually understand it was placed within the `foo` module.

There's one thing I'm not sure we've talked about though, how does this play with method syntax? (Maybe I've missed this)

A:
```c++
fn void foo::MyStruct.bar() { ... }
```

B:
```c++
fn void MyStruct.foo::bar() { ... }
```

Or is this solely for free functions?

**Comment by joshring** [comment]
So there is a hint that a module foo exists, but to my eyes there is no definition I would recognise for foo

**Comment by lerno** [comment]
This thing is valid today:
```c
fn void std::core::String.new_thing(self)
{}
```
And is nothing special, just an unambiguous way to write:
```c
fn void String.new_thing(self)
{}
```

**Comment by joshring** [comment]
> but it would be mainly for the occasional constructor function and to make converted constant enums from C APIs more friendly.

>  But anyway, I don't think foo::bar() is too crazy of a concept in the grand scheme of things and :: makes it more obvious of what it could be doing

I think open for extension is _fine_, but implicitly organising code seems like a mis-step because it can be over-used and become hard to maintain.

Not everything added is used in the way you expect is my concern.


I think one of the hallmarks of successful features languages is easily being able to find the definitions of concepts in the code. That's why things like C/C++ macros are so hard, because they can nest and you don't know where the code is, leading to great complexity.

Perhaps not as bad as that, but could be easily misused.

**Comment by lerno** [comment]
Having investigated the complexity and the look of it, it looks like it's not worth it.
