### ISSUE TITLE
Handling strings from a c background is painful

### ISSUE THREAD

**Issue by Nizarll** [c3lang/c3c#1612]
i feel like this is mostly a skill issue , but it is an issue nonetheless which becomes even harder to handle strings with so much implementations of the same thing like zstring dstring string slices char[] and char* which really becomes painful when one cannot be implicitly casted or explicitly casted at all , which might be logical since some hold size and some dont.
but it becomes harder to implement things like the use of pointer arithmetic to check whether a string contains a substring at a specific index 
https://godbolt.org/z/cdE7Yezo6

**Comment by lerno** [comment]
A `ZString` is a `char*`, it's just distinctly typed, so that to convert a `char*` to a `ZString` you need a cast. This cast is essentially there to "ensure" that the `char*` is zero terminated. A ZString can trivially be turned into a String, there are convenience methods for it. To turn a String into a ZString is a bit less straightforward, because there might be a need to add an additional zero at the end. This is similar to the problem when you try to return a substring from a string in C.

You should be able to use ZString with all C APIs that take `char*`. Using a `DString`, which is basically a dynamic string builder, you can always grab a ZString or String view without additional allocations.

Typically you should never use `char*` directly but use a `ZString`, but they are the same.
Similarly, don't use `char[]`, use `String` even though they are the same.

So you have:
1. String - the normal thing to use, it can be sliced and still get a String etc.
2. ZString - what you use if you have a zero terminated string. It is a char* with a fancy name.
3. DString - if you want to have a dynamic string that handles its own memory and which you can edit back and forth, use this one.

**Comment by Nizarll** [comment]
thanks for the clarification ! i understand now the difference between these distinct types however i just find weird that the standard library implements dstring which manages its own memory which is basically raii whilst the c3lang documentation website states that it should not be a thing .
aside from that i think it would be nice to have that in the documentation or have this issue pinned so that people with similar confusion can be enlightened !

**Comment by lerno** [comment]
You have to free a DString if you add to it. It's just that you don't need to allocate memory for it if it's empty.

**Comment by Nizarll** [comment]
what about pointer arithmetic is it mandatory to go through : string -> char* -> do ptr arithmetic -> cast back to string or zstring ? since pointer airthmetic is not allowed on distinct zstring and string types ?

**Comment by lerno** [comment]
> what about pointer arithmetic is it mandatory to go through : string -> char* -> do ptr arithmetic -> cast back to string or zstring ? since pointer airthmetic is not allowed on distinct zstring and string types ?

Typically you do slicing operations on String, so let's say you want to get the string with an offset of +3 compared to the current slice, then `my_string[3..]` is the standard way of doing that. If you want to get the pointer to the character at position 3, again use the standard `&my_string[3]` as if it had been an array. For ZString there might be some omissions in the compiler I should have a look at: `&my_zstring[3]` should work properly but it doesn't.

**Comment by lerno** [comment]
See #1621 for the fixes scheduled for ZString.

**Comment by lerno** [comment]
Can I close this since these should now be addressed?
