### ISSUE TITLE
Interesting behavior when `tmp` name is used as a newly init project

### ISSUE THREAD

**Issue by stefanos82** [c3lang/c3c#1648]
It's really an interesting behavior; it even prevents me from building the newly init-ed project!

Command is `c3c init tmp` and with `c3c build`, you should see `Cannot create exe with the name 'build/tmp' - there is already a directory with that name.` as an output.

**Comment by stefanos82** [comment]
Hmm, the issue can be resolved by renaming `targets`:

```js
"targets": {
    "tmpv1": {
      "type": "executable"
    }
}
```

**Comment by lerno** [comment]
Yes, if you don't specify a dir for your object files it will default to "tmp"

**Comment by stefanos82** [comment]
Interesting; you mean the `--obj-out` flag?

**Comment by lerno** [comment]
Yes, that's the one.

**Comment by stefanos82** [comment]
I have just tried it; it does not work, unless I used it incorrectly: `c3c init mydemo --obj-out foo`

When I run `c3c build` it does not create any `foo` directory under `build`.

**Comment by stefanos82** [comment]
I have even tried `c3c init dokimi --build-dir mynewdir --obj-out foo` and still nothing; it generates the default project skeleton.

**Comment by lerno** [comment]
Those are for build/run not for init.

**Comment by stefanos82** [comment]
...wait, what?! This creates a mess!

Here's the output:

![image](https://github.com/user-attachments/assets/befc7cb1-f3bc-487f-85f5-e2de3e696c51)

Also, as you can see, the `tmp` no longer exists inside `build`, but I expected `foo` to be `tmp`'s place; also, why am I still getting `build` since I told it to use `mynewdir` explicitly?

**Comment by lerno** [comment]
Well, there are a lot of directories!
1. Build directory: here is where anything ends up that is created. The object files end up in a sub directory since they're always deleted after use, but there are other things, like llvm or asm output. They also end up in the build library
2. The object output dir – will be deleted after build, defaults to build/tmp
3. The llvm output dir – if you emit llvm IR it ends up here, this defaults to the build/llvmir directory. Files not cleaned
4. The asm output dir - if you emit asm it ends up here, like LLVM files defaults to the build/asm directory and files are not cleaned.

If you want to get rid of the build directory you can set it to '.', but be sure to set all the other dirs in that case.

**Comment by lerno** [comment]
Oh, you might be right in that tmp isn't deleted. It's cleaned though. There is a bit of discussion on how to do this properly. Consider for example that you set the output of your .o files somewhere and the cleanup just cleans all the files in the directory... it might be super bad.

**Comment by stefanos82** [comment]
Logically, those who want to retain their `.o` files, will not run the `c3c clean` command for the sake of not risking losing their object files; but those who do want to clean their project completely, they expect everything to get clean, the executable included.

**Comment by lerno** [comment]
The .o files are today automatically cleaned up because the alternative is that `c3c compile-run` barfs the entire set of .o files into the current directory.

If I accidentally set the build output to the wrong directory then this risks deleting the directory on clean. Something that has been discussed was that to use the heuristic that if a directory is created as part of the compilation process it's fine to delete at the end. I don't remember the issue that discussed this, but I welcome participation in hashing out the exact rules.
