### ISSUE TITLE
Add support for foreach operator overloading

### ISSUE THREAD

**Issue by lerno** [c3lang/c3c#194]
Should it have an underscore prefix?

    macro Vector._foreach_index(Vector* vector, $by_ref, $reverse; @body(index, value))
    macro Vector._foreach(Vector* vector, $by_ref, $reverse; @body(value))

Or without?

**Comment by lerno** [comment]
This turns out to be a dead end as it cannot express labelled break.

**Comment by lerno** [comment]
New proposed syntax for overloading:
```c
struct FooIterator
{
    Foo *f;
    usize index;
    usize len;
}

macro FooIterator Foo.iterator(Foo* f)
{
    return FooIterator({ f, 0, f.x.len() });
}

macro bool FooIterator.test(FooIterator *it, int &value)
{
    if (it.index >= it.len) return false;
    value = it.f.x[it.index];
    return true;
}

macro void FooIterator.incr(FooIterator *it)
{
    it.index++;
}
```

**Comment by lerno** [comment]
Variant: Provide the original object everywhere:
```
struct FooIterator
{
    usize index;
    usize len;
}

macro FooIterator Foo.iterator(Foo* f)
{
    return FooIterator({ 0, f.x.len() });
}

macro bool FooIterator.test(FooIterator *it, Foo &f, int &value)
{
    if (it.index >= it.len) return false;
    value = f.x[it.index];
    return true;
}

macro void FooIterator.incr(FooIterator *it, Foo &f)
{
    it.index++;
}
```

**Comment by lerno** [comment]
Variant, collapse test and incr into a single `next`


Collapse test / incr into a `next`

```c
macro bool FooIterator.next(FooIterator *it, Foo &f, int &value, $first)
{
    $if (!$first):
      it.index++;
    $endif;  
    if (it.index >= it.len) return false;
    value = f.x[it.index];
    return true;
}
```

**Comment by lerno** [comment]
As a complement the iterator may implement `test_index`

`macro bool FooIterator.next(FooIterator *it, int &value, &index)`

This supports `foreach (int index, int value : f)` syntax.

**Comment by lerno** [comment]
By default when `foreach (x : foo)` is seen, this is converted into `foreach (x : foo.@iterator())` and `foreach (index, val : foo)` is converted into `foreach(index, val : foo.@index_iterator())`

It is also possible to explicitly provide an iterator: `foreach(index, val : foo.iterator())`. Note that it will first check whether the type itself provides an iterator, after that try to interpret the value as an iterator. (Or should it be vice versa?)

Either a function or a macro is allowed to provide the iterator.

**Comment by lerno** [comment]
Let's say we want to iterate over something in reverse, we can then provide an explicit reverse iterator:

```c
foreach (x : foo.riterator()) { ... }
```

**Comment by jfecher** [comment]
Of the variants above, I like the version with `next` the best since it cuts down on the amount of methods you need to remember to implement. What is the reasoning for the `first` parameter to `next` though? Seems like it should work without it:
```c
macro bool FooIterator.next(FooIterator *it, int &value)
{
    if (it.index >= it.len) return false;
    value = f.x[it.index];
    it.index++;
    return true;
}
```

**Comment by lerno** [comment]
The idea with "incr-test" is to mirror how a for loop works, so essentially it would reduce to:
```c
int value;
for (FooIterator it = foo.@iterator(); it.@test(value); it.@incr()) 
```
It's then fairly natural that some of these can even be left out.

Having a macro take a $first parameter allows doing something lazily, like priming the data in the first pass.

I am also considering adding more optional function/macros:

```c
macro void FooIterator.enter_iterator(FooIterator *it) ...
macro void FooIterator.enter_scope(FooIterator *it) ...
macro void FooIterator.exit_scope(FooIterator *it) ...
macro void FooIterator.exit_iterator(FooIterator *it) ...
```

These could then essentially be inserted in this way if they are present:
```c
{
  FooIterator it = foo.@iterator();
  {
     defer it.@exit_iterator();
     it.@enter_iterator();
     int value;
     for (; it.test(&value); it.incr())
     {
        defer it.exit_scope();
        it.enter_scope();
        ... code ...
     }
  }
}        
```

Thanks to how defer works this will give possible callbacks to do cleanup / priming for every loop and for the foreach itself.

**Comment by data-man** [comment]
I like C++20 iterator concepts and D's ranges.
There should be a way to distinguish between forward, backward and random-access iterators.

**Comment by jamestmartin** [comment]
With iterators I can think of these basic operations:

* test if there is a next (or current) state
* continue to the next state
* generate a result from the current state
* fetch the current result

I would suggest using one of these options:

1. just `next` (test, continue, generate, & fetch)
2. `next` (test, continue, generate, & fetch), `skip` (test & continue)
3. `has_next` (test), `next` (continue, generate, & fetch)
4. `has_next` (test), `next` (continue, generate, & fetch), `skip` (just continue)

These are some things I think may lead to problems, especially if iterators may perform side-effects other than mutating themselves:

1. Separating `continue` from `generate`. Should side-effects be performed when you continue to the next state or when you generate a new result? Should side-effects be performed every time you call `generate`, should calling `generate` repeatedly be a no-op, or should `generate` only be callable at most once (introducing a new potential type of bug)? How much state will you have to carry between these calls to keep them separate and how much will you have to cache?

2. Separating `generate` from `fetch`. You are now forced to store the result in your iterator between the `generate` and `fetch` call. It may also be possible to try to fetch a result without generating it, which introduces a new possible kind of bug.

3. Not separating `test` from `generate`. You do not know if side-effects will be performed before calling `generate`, and if you're using an iterator in something other than a foreach loop you may wish to know if there will be another result before you compute it.

4. Not being able to `continue` without `generate`. If you know you don't need the result and generating a new result may be expensive, you're just wasting computation time and/or IO. The function to continue without generating can just default to the "continue and generate" function for the usual case when it is not expensive.

In my opinion `incr`/`test` is a poor solution because it is unspecified where side-effects should occur, it is unspecified how it should behave if `test` is called multiple times, you cannot know if there is a next result without computing it, and you cannot skip generating a result, and even if you forbid side-effects and assume computations aren't expensive, it's unclear to me what benefit it has over a different or simpler solution.

**Comment by jamestmartin** [comment]
Oh, also, just as a matter of interest, this is the maximal possible iterator interface I can think of:

* `has_next_compute`
* `has_next`
* `incr`

**Comment by lerno** [comment]
> I like C++20 iterator concepts and D's ranges.
> There should be a way to distinguish between forward, backward and random-access iterators.

This is not so much for full fledged iterators as it is to provide a way to do foreach over any set of items.

On related issue is whether iterators allow "delete". But if we look at foreach, the iterator is not actually available, so any interfacing with the iterator actually would have to be using a special construct!

**Comment by lerno** [comment]
> Of the variants above, I like the version with `next` the best since it cuts down on the amount of methods you need to remember to implement. What is the reasoning for the `first` parameter to `next` though? Seems like it should work without it:

It works without it, but with the parameter we allow switching strategy between first and consequent actions. For example, no need to allow a pointer to beyond the end of an array. For simplicity's sake it should probably go.

**Comment by lerno** [comment]
A new foreach has now been implemented based on [] overloading.
