### ISSUE TITLE
defer

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#2]
defer is very useful, but could potentially be even more. (I intentionally ignore defer for errors for now.)

--------------

It may be handy to cancel a defer sometimes.

```
func void test(int x)
{
    // defer may produce a symbol, which could be used inside the function
    some-symbol-name = defer printf("A");
    if (...) {
      un-defer[some-symbol-name]; // this cancels the defer action
     }
     if (...) {
      un-defer[some-symbol-name]; // multiple cancellation is OK
     }
}

```

un-defer would replace manual fiddling with boolean flags. 

---------------

It may be also handy to change what is being deferred.

```
func void test(int x)
{
    some-symbol-name = defer printf("A");
    if (...) {
      re-defer[some-symbol-name] printf("B"); // use this action, not the previously set one
     }
    if (...) {
      re-defer[some-symbol-name] printf("C");
     }
}

```

-------------------

Non-scoped defer. The ability to have _function scoped_ defer at any place.

```
func void test(int x)
{
    if (...) {
      // will fire when function ends, not when the current scope does
      defer<function-scope>  printf("A"); 
     }
}

```

Defer action wouldn't be allowed to use local scope variables.

Symbol for such defer would also have function wide visibility:
```
func void test(int x)
{
    if (...) {
      my-symbol = defer<function-scope>  printf("A"); 
     }
    if (...) {
      un-defer[my-symbol];
    }
}
```

----------------

When defer symbol is generated, it has to be used. Unused symbol is error. Symbols should be unique per function. Deferred block should not contain ordinary return or error return.

Defer placed directly inside defer section should not be allowed, to keep the code sane.

**Comment by lerno** [comment]
**Cancelling defer**
I'll have to think about it. It's actually not difficult to do, since conditional defer actions are needed anyway to correctly handle `goto` together with defer. I would need to see some good usecases for it though.

Note that `defer catch` together with `defer` should handle most cases where having different paths might be useful. So any example needs to clearly show where those are not sufficient.

**Function scope defer**
The downside of function scope defer is that the size requirement is unbounded and it works very differently from a normal defer.

Consider this code:
```
func void test()
{
    for (int i = 0; i < 10000000; i++)
    {
        defer<function-scope>  printf("%d\n", i);
    } 
}
```
Here there is a need to allocate space for the lambda captured by the 10000000 defers to be executed at function end. Although this is clearly pathological, it shows what's needed for the compiler. Note that the behaviour above can be handled with a defer declared at the very top which then uses an explicitly accumulated array:

```
func void test()
{
    int[] buffer;
    defer for (int i in buffer) printf(printf("%d\n", i);
    for (int i = 0; i < 10000000; i++)
    {
        buffer []= i;
    } 
}
```

Perhaps you do not propose allocating lambdas on the heap, if not, then how do you propose to solve it?

**Comment by PavelVozenilek** [comment]
About `defer catch` :  I need to think about the errors, so I'll avoid this for now.

-----------

Multiple `defer<function-scope>` inside a loop. Yes, that's a problem. Simple cases like this could be probably refused by the compiler, more complicated cases would be responsibility of the developer.

------------

defer implemented as closure: I thought defer block is code simply inserted at the end of its scope, not something with captured environment.  This would be simpler to implement and simpler to think about and sufficient for use. If someone want's a staled value, this is a very special need and he should create helper variable for it.

I think languages like Jai implement defer in this simple way.


I generally do not like closures, continuations and similar things. Complicated comp-sci trick for next to nothing.

**Comment by lerno** [comment]
Yes, the normal way (Jai, Zig, Nim) to implement a defer is by scope, this leads to similar semantics as RAII in C++, and is relatively easy to implement (although goto, continue, return and break creates a bit of complexity).

Function scope defers (this is what Go uses by the way) works quite differently. They essentially work like a stack, with defer actions to be executed on function return. In some ways this can be easier to reason about, but the way to implement it is by stacking things onto a list in some manner, for example through lightweight lambdas. See for example: https://blog.golang.org/defer-panic-and-recover 

Because of the complexity and difference in execution model I was not planning on adding Go style function scope defers, but only the normal scoped defers (like Jai, Zig, Nim)

**Comment by PavelVozenilek** [comment]
> Function scope defers (this is what Go uses by the way) ..

Ahh, I see now.  Probably bad idea of mine.

**Comment by lerno** [comment]
Please file this on c3docs if it is still a proposal.

**Comment by lerno** [comment]
It's possible that one could use labels to cancel defers:

```
defer FOO: { ... }
...
defer FOO = 0;
```

Or some similar syntax. I don't want to add another keyword. Maybe this is possible:

```
defer FOO: { ... }
...
defer FOO: { ... }
```
