### ISSUE TITLE
Compiler allows implicit casts between signed and unsigned integer types?

### ISSUE THREAD

**Issue by bumbread** [c3lang/c3c#219]
This code

```
long b = -3;
ulong a = b;
io::printf("%lu", a);
```

Compiles and when ran, prints `18446744073709551613`

**Comment by lerno** [comment]
Yes, this is by design.

**Comment by lerno** [comment]
I can elaborate: it turns out that with the choice of removing overflow checking and making signed overflow well defined and 2s complement, requiring casts creates unnecessary complexity without safety. For example:

    uint x = ...
    uint y = ...
    int z = x - y;

Here are not gaining anything by requiring casts.

    int x = -1;
    uint y = x;
    uint z = 100 + y;
    
Again assuming 2s complement, the uint / int is only relevant when performing division and multiplication. So this is a problem:

    int x = ...
    uint y = ...
    uint z = x / y;

Here the types actually matter. Note that unlike in C, this will actually cast y to *signed*. Which will make this mostly correct. Any error only occurs on y > INT32MAX. Which should be caught elsewhere anyway, and adding an explicit cast (which most people will do without thinking) isn't helping any.

So reviewing this back and forth I found this solution to be the reasonable and less error prone one.
