### ISSUE TITLE
Proposal: Multi-submodule import support

### ISSUE THREAD

**Issue by xpyxel** [c3lang/c3c#354]
In rust, it's possible to import multiple submodules/imports by using curly braces like so:

```rs
use std::{io::Error, fmt::Error};
```

This syntax/ability allows to clean up imports quite a bit in my opinion, as the amount of imports can grow immensely over time, this problem occurs in a variety of languages, such as Java, Zig, C#, generally any language that suports nested import paths, i.e. `hello.world.this.is.a.submodule.path`, where you need multiple submodules imported.

```go
// current
import std::io;
import std::mem;
import std::fmt;

// proposed
import std::{io, mem, fmt};
```

This would also make it easier to find what parent module a submodule belongs to, if a long list of imports are in a file, i can just go to the group where the submodule is imported.

**Comment by lerno** [comment]
Note though that there are no intrinsic relationship between modules that depends on the path. What that means is that the path is basically a name. `std::io` is just as related to `foo::bar` as it would be `std::baz`. So implying that would be incorrect.

## Related ideas
Two related ideas must be considered:
1. Specific imports. This is more important where the functions are usually imported without prefix. 
```c
import some_module : some_function; // Only import some_function
```
This is currently *not* in. I removed it because it did not seem useful.
2. "Implicit imports": imports could be determined from usage rather than "import". The mandatory prefix on functions supports this, although it increases the risk that types will need to be used with prefixes. There are various ways issues could be mitigated. But this would then be a fairly import free style. It has its benefits and its downsides. In particular, the "import" does simplify the IDE's ability to parse files in isolation.

## Syntax:
Due sub modules not being related to the parent, an alternative would be to simply allow imports be stated as a list:
```c
import std::io, std::mem, std::fmt;
```

**Comment by xpyxel** [comment]
> Note though that there are no intrinsic relationship between modules that depends on the path. What that means is that the path is basically a name. `std::io` is just as related to `foo::bar` as it would be `std::baz`. So implying that would be incorrect.
> ## Related ideas
> 
> Two related ideas must be considered:
> 
>     1. Specific imports. This is more important where the functions are usually imported without prefix.
> 
> 
> ```c
> import some_module : some_function; // Only import some_function
> ```
> 
> This is currently _not_ in. I removed it because it did not seem useful. 2. "Implicit imports": imports could be determined from usage rather than "import". The mandatory prefix on functions supports this, although it increases the risk that types will need to be used with prefixes. There are various ways issues could be mitigated. But this would then be a fairly import free style. It has its benefits and its downsides. In particular, the "import" does simplify the IDE's ability to parse files in isolation.
> ## Syntax:
> 
> Due sub modules not being related to the parent, an alternative would be to simply allow imports be stated as a list:
> 
> ```c
> import std::io, std::mem, std::fmt;
> ```

The list method could work, due to the relation things the repeated std:: seems tedious but since they are just names it'd have to be this way.

**Comment by lerno** [comment]
Another alternative is trying an implicit import scheme of some kind.

**Comment by lerno** [comment]
I've added the ability to use `import foo, bar, std::io;` Try it out @xpyxel if you think it's good enough.

**Comment by lerno** [comment]
We can reopen this if it's not sufficient, ok?
