### ISSUE TITLE
operator precedence

### ISSUE THREAD

**Issue by PavelVozenilek** [c3lang/c3c#7]
Righ now the documentation presents this simple table:

> 1. (), [], ., postfix ++ and --
> 2. prefix -, ~, prefix *, &, prefix ++ and --
> 3. infix *, /, %
> 4. <<, >>
> 5. ^, |, infix &
> 6. +, infix -
> 7. ==, !=, >=, <=, >, <
> 8. &&, ||
> 9. ternary ?:
> 10. =, *=, /=, %=, +=, -=, <<=, >>=, &=, ^=, |=
> 11. ,
> 

It feels like a part of some mnemonic quiz.

Is this thing _really_ needed? After decades of programming I am unable to recall operator priorities in C.

----------
_What do the different languages do?_

* One implementation of Prolog has _1,000_ priorities available for custom operators. I am not kidding. Nobody uses Prolog.

* Smalltalk does not use priorities: `1 + 2 * 3` is `9`, not `7`. If you don't like it, add parenthesis.  Nobody uses Smalltalk.

* Lisp does not have operators and is missing the whole problem. Unfortunately, nobody uses Lisp.

------------
_What would be the simplest, most natural and most readable solution?_

Use parenthesis for all binary operators, always, without exception. It clears all doubts, ambiguities and misunderstandings. Sane programmers do it already. Programmers coding in several similar languages _must_ do it.

Examples:

```
// When parenthesis are not needed:
a + b + c // does not need parenthesis, evaluated left to right, as (a + b) + c
a - b - c  // ditto
a / b / c  // ditto
a * b * c  // ditto

// When parenthesis are required:
a + (b * c)
(a + b) * c
if ((a < b) && (c <= d)) ...
(a << 2) + 1
x *= (a * 2)
```

In addition to simplicity and readability, there is one more advantage: order of evaluation can be fixed  (unlike C). 
The compiler then won't be able to reorder expressions, bringing in unexpected integer overflow/underflow or loss of FP precision. This is important if the language doesn't care about overflow/underflow. (Important topic which should be documented in detail.)

The result C could could reflect this predictability. (This is yet another important topic. Do C promotion rules impact result of C3 expressions, or not?)

-----------
_Are there some disadvantages?_ 
Big one: no IOCC like contests.
If an expression has way too many parenthesis, it is signal to split it into simpler parts.

---------

Btw, operator `,` (comma) in C is miscarriage and should not be allowed.

**Comment by lerno** [comment]
The `,` operator is gone actually.

Parenthesis "always" is the way of Pony and other languages. I personally think that's going too far. In fact the rules above are designed to remove some parenthesis and add others. Unlike C, each group of operations have their own precedence. I think C has 15 precedence levels, C3 trims that down to 10 if we remove the comma.

It could be argued that `&&` and `||` have the same precedence as `==` etc. If so then parenthesis would be needed for `a < b && c > d`. Personally I'm likely to put parenthesis around them, but in the case of `x & mask == mask` I'm actually making that work (C would of course require `(x & mask) == mask`).

I could consider requiring parenthesis around left-to-right things like `a < b < c`, since they're unclear (for the non obvious I'm simply doing left-to-right) in C3.

**Comment by PavelVozenilek** [comment]
Yes, this is (probably the only) thing that Pony got right, IMO.

Here's an argument for parenthesis: if someone will use C3 during the next decade, it won't be his first and only language.  If C3 is strict, he wouldn't make these silly and unavoidable mistakes and the perception of the language will be positive.


Anyway, there's a cop out to have both: whether the compiler enforces parenthesis or not could be set as project wide flag in mandatory project configuration (which I plan to propose some day). I do not care too much about the single file use case.

**Comment by lerno** [comment]
I think it's unlikely that someone will use C and make mistakes in C3. `a >> 1 == 2` is extremely unlikely to be correct when seen in C. Nor is this code very likely: `a > 1 == b < 1`. So I don't think people coming from C will actually have any problems with this. At most people could have written `a >> 1 + b` and actually intending it to be `a >> (1 + b)` so that's a small gotcha.

But yes, this could certainly be a warning/error if people want it.

**Comment by lerno** [comment]
Please file this on c3docs if still needed.
