### ISSUE TITLE
Inlined type is not recognizing and compiler demands a cast

### ISSUE THREAD

**Issue by kcvinker** [c3lang/c3c#715]
Hi, this is the callback type. 
`define EventHandler = fn void(Control* c, EventArgs* e); `

And this is the stucts

`struct Control { ...} // Base type
`

`struct Form { // Derived type `
`    inline Control control;`
    `    ...`
    `    EventHandler onLoad;`
`}`
But we need to use cast here.
`frm = newForm("Windows Gui Lib");`
`frm.onLoad = (EventHandler)&frmOnLoad;`
When we use the derived type in function signature.
`fn void frmOnLoad(Form* f, EventArgs* e) {`
	`    io::println("form loaded");`
`}`

**Comment by lerno** [comment]
After thinking about this for a few weeks, I think it's probably better to have the explicit conversion. The reason is both implementational complexity (a much more complex lookup must be done to match things), but also it's somewhat inconsistent other parts of the implicit casting.

We can reduce this to a simple example:

```c
define Foo = fn void(Control* c); 
fn void test(Form* f) { ... }

Foo f = (Foo)&test;
```
In this case we have to think about the concepts of covariance and contravariance.

`f(some_control)` will be accepted, which is trying to pass a control to something that expects a form(!) so this would actually possibly be wrong since nothing will test the type.

We can then consider the other way around:
```c
define Bar = fn void(Form* c); 
fn void test(Control* f) { ... }

Bar f = (Bar)&test;
```
Here this is actually safe! Because we can only ever call `f` with a Form, which is a subtype of Control. So this potentially could work, but is very limited in use and nothing works like that in the rest of the language. Like covariance and contravariance in Java, this would most likely simply baffle people when they run into it anyway.

So with this taken into account (complexity in implementation, hard to understand behaviour), it's probably best to drop it.
