### ISSUE TITLE
[SUGGESTION] FULLY featured foreach loop

### ISSUE THREAD

**Issue by Godnyx** [c3lang/c3c#79]
I know the forech loop is in the todo list and I just wanted to say that PLEASE make it a fully featured for loop alternative. D also has the foreach loop (I don't know if you were inspired from there) but i can go only one step and from smaller numbers to bigger numbers. I will suggest a few things and If you want you can consider making them. 

Syntax:
for (a; 10) # a is the variable used for the loop, when using one number for the loop, it always starts from 0 and goes all the way to the number minus 1 (so it will be easy to loop thorough an arrays length).
for (a; 1,11) # The same as before but this time it starts from 1 and goes to the end minus 1. It will also be SUPER cool if when someone starts with the bigger number and ends with a smaller number, it automatically when in minus 1 step but this is way advanced and not very important
for (a; 0,11,2) # Like before but the third number is the step.

**Comment by lerno** [comment]
@Godnyx It's possible to use the slice syntax for this. If you have an array `a`, then you can do `a[..10]` and you get a zero cost substring you can do foreach over. You can count from the back of the array: `a[..^2]` would set the `len - 2` as the top (excluded) index.

Unfortunately you can't `stripe` a subarray (i.e. taking every n values), nor create a reverse view of it. The reason is that it would require a more complex model for the subarray type that would have greater runtime cost for all uses of substrings.

**Comment by Godnyx** [comment]
Thanks a lot for your answer and I wish you the best of luck with the project! Cheers mate!
