### ISSUE TITLE
assertion failed with invalid code returning error and recursive call

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#811]
The following (invalid) code produces this error:
> Assertion failed: (context->current_block), function llvm_emit_cond_br_raw, file llvm_codegen_instr.c, line 9.

Note that in my original code, if I use a local fault, it segfaults when running `c3c compile-test`.

```
module test;
import std::io;

struct Foo
{
    int index;
}

fn bool! Foo.foo(Foo *f)
{
    return IoError.EOF?;
    return f.foo();
}

fn void main()
{
    Foo foo;
    foo.foo()!!;
}
```

**Comment by pierrec** [comment]
Also, in my original code, the returned error was guarded by a condition (and the code was valid).

**Comment by lerno** [comment]
The problem here was poor control from analysis. Because dead code wasn't really eliminated until codegen, this was mostly a non-problem. So the simple fix here would be to fix the problem in codegen. However, warning on dead code revealed sloppy control flow, so fixing that is probably a better idea, and that has taken a deeper review.
