### ISSUE TITLE
returned type mismatch not detected

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#815]
```
module testing;

fn void main()
{
    foo(-1);
}

fn usz foo(isz x)
{
    return x;
}
```

**Comment by lerno** [comment]
Signed to unsigned conversions are silent by design.

This may seem odd, but there are some additional semantics that ties into this:
1. Comparison between unsigned and signed values are always safe, no type conversion will happen.
2. Type promotion will in general preserve the signedness, otherwise it will prefer signed over unsigned. This behaviour is different from C.
3. Because 2s complement is mandated, the remaining security risks and bugs caused by unsigned is for the majority of situations only a risk when *dividing* a signed value by an unsigned value or vice versa. It would be possible to make this conversion an error.

**Comment by pierrec** [comment]
I see. Is this documented? I have read much of the docs and I either missed it or didnt remember it.
Thanks for the clarification!
