### ISSUE TITLE
missing method when generic module used with distinct

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#833]
> Error: There is no field or method 'FooInt.set'.

```
module testing;
import std::io;
import foo;

fn void main()
{
    FooInt foo;
}

def FooInt = distinct Foo(<int>);

struct Bar
{
    FooInt list;
}

fn void Bar.set(&self, int x)
{
    self.list.set(x);
}

module foo(<Type>);

struct Foo
{
    Type x;
}

fn void Foo.set(&self, Type x)
{
    self.x = x;
}
```

**Comment by lerno** [comment]
This is... sort of correct. "distinct" is making a new type as if you'd done:

```c
struct FooInt
{
   Foo(<int>) inner;
}
```

In the above, using inline will make `inner`'s functions and fields transparently available:

```c
struct FooInt
{
   inline Foo(<int>) inner;
}
```

The same holds for `distinct inline`, so this should work:

```c
def FooInt = distinct inline Foo(<int>);
```

BUT it didn't. So that is fixed now.

Note that `distinct inline` allows you to pass a `FooInt` wherever a `Foo(<int>)` is accepted, but not vice versa. Usually when creating a generic one would not use "distinct" though.

**Comment by pierrec** [comment]
OK it makes sense. It used to work though, so I was surprised but didnt really think about it.

**Comment by lerno** [comment]
You might not have used `distinct`?

**Comment by pierrec** [comment]
Pretty sure I did.

**Comment by lerno** [comment]
Looking at this, I discovered that previously using `distinct` for generic types was actually ignored. That is why it worked before.
