### ISSUE TITLE
runtime segfault

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#839]
Getting a segfault when connecting to the server (http://localhost:8081/) started with [this](https://github.com/pierrec/pepper).

> c3c build && ../pepper
> ...
> zsh: segmentation fault  ../pepper

> c3c build --no-strip-unused&& ../pepper
> ...
> zsh: segmentation fault  ../pepper

**Comment by lerno** [comment]
As far as I can track this, it's writing to the body, but the ByteReader's data is corrupted, so the data and index have extremely large values. So when the read method tries to read this into the buffer, you get a segmentation fault because bytes[] and index in ByteReader is corrupted. For example I get index = 140701999108736 and bytes.len = 4349690672. They were originally 0 and 11. I'll see if I can trace where the overwrite happens.

**Comment by lerno** [comment]
Here is the error:
```c

fn void handler(HTTPRequest* req, HTTPResponse* resp)
{
    resp.status = 200;
    ByteReader body;
    body.init("Hello world");
    resp.body = body.as_stream();
}
```
You allocate the ByteReader on the stack, convert it to a stream, but `as_stream()` is a wrapper and does make a copy of body to the heap. So as soon as this goes out of scope it gets corrupted.

**Comment by pierrec** [comment]
Ah yes of course. Sorry for the noise.

**Comment by lerno** [comment]
You should be able to attach a debugger to the exe and trace this.

**Comment by pierrec** [comment]
Thinking about it, shouldnt the bound checks have been triggered?

**Comment by lerno** [comment]
You're thinking about that bytes[index] should have triggered bounds check because index > len? It doesn't because of the first check, so that will just be an IoError.EOF in the cases it happens. This is - by the way - why it would work sometimes when rearranging the code a little: for those cases index > len, and IoError.EOF was thrown instead. So it becomes quite the Heisenbug:
```c
	if (self.index >= self.bytes.len) return IoError.EOF?;
	usz len = math::min(self.bytes.len - self.index, bytes.len);
	if (len == 0) return 0;
	mem::copy(bytes.ptr, &self.bytes[self.index], len);
	self.index += len;
```

**Comment by pierrec** [comment]
OK.
