### ISSUE TITLE
optional reassignment not taken into account

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#868]
As per our discussion on Discord, the following does not work as expected.
> main.c3:16:13: Error: The expression may not be an optional, but was 'char!'.

```
module testing;
import std::io;

fn void! main()
{
    usz x;
    char! c = read();
    if (catch err = c)
    {
        case IoError.EOF:
            c = 0;
            break;
        default:
            return err?;
    }
    switch (c)
    {
        case 'a': x = 1;
        case 'b': x = 2;
    }
}

fn char! read()
{
    return 1;
}
```

**Comment by lerno** [comment]
This is actually working as expected. If you write `int! c = 0;` Then similarly `c` is `int!` even if we can see that in this case static analysis clearly sees it is non-optional.

The reason is not one of analytic complexity, but because it should be deliberate and simple to understand when implicit unwrapping happens.

If we think about writing a macro and inside of it `c` is declared to an int constant in one case, and an optional in another. If static analysis dictated the type, then the following code would also need to be different.

Finding it caused lots of problems combining extended flow typing with macros, I decided that only certain constructs could cause flow typing unwrap: `if try` and `if catch`. There are lots of ways to provide conveniences around it.

**Comment by pierrec** [comment]
I see, I understand the reasoning. My assumption was that `if catch` would unwrap it nonetheless.
I have found a workaround without a macro by restructuring the logic.
