### ISSUE TITLE
comptime subscripts evaluation

### ISSUE THREAD

**Issue by pierrec** [c3lang/c3c#955]
Currently the following will produce an error:

> $if $m.nameof[0] != '_': ... $endif

This issue is to keep track of this feature.

**Comment by lerno** [comment]
This should work now.

**Comment by pierrec** [comment]
It does except when processing a struct where there is a union:
> Error: The index (0) is out of range, the length is just 0.
```
struct Foo
{
	int x;
	union {
		uint y;
		bool z;
	}
}

fn void! main()
{
	Foo foo;
	$foreach ($m : Foo.membersof)
		$if $m.nameof != "" && $m.nameof[0] == '_':
			foo.x = 1;
		$endif
	$endforeach
}
```

**Comment by lerno** [comment]
An anonymous union or struct member has an empty name. Thus what you are doing is essentially `""[0]`. Traversing the inner struct/union is possible but must be done explicitly.

**Comment by pierrec** [comment]
> An anonymous union or struct member has an empty name. Thus what you are doing is essentially `""[0]`.
Yes hence my check for the emptiness of the name. Seems like it doesnt matter lol.
Any way around that?

**Comment by pierrec** [comment]
well I can check if it is a union first. Will rearrange my logic. All good.

**Comment by lerno** [comment]
Oops, that's what I get for typing an answer on the phone.

Ok, so what you're running into is a different issue: that semantic checking is done together with constant folding. A binary expression like && is completely analyzed before evaluation, which means the semantic failure to fold the right hand side causes a compile time regardless of the left hand side.

So in order to make this code work, use nested $if or equivalent. So in the outer $if, test is it is non-empty, then inside, test what it starts with.

There are interesting reasons why && and || work like this.
